### ISSUE TITLE
Bug in example

### ISSUE THREAD

**Issue by jennysjaarda** [ramiromagno/gwasrapidd#5]
There seems to be a bug in the example on the github README.md. 
It all works until the following: `variants <- get_variants(study_id = 'GCST002305')`
Then I get the error: 
```
Error: Tibble columns must have consistent lengths, only values of length one are recycled:
* Length 0: Columns `chromosome_name`, `chromosome_position`
* Length 15: Columns `gene_name`, `distance`, `is_mapped_gene`, `is_closest_gene`, `is_intergenic`, … (and 4 more)
Run `rlang::last_error()` to see where the error occurred.
```

**Comment by ramiromagno** [comment]
Thank you for reporting this @jennysjaarda!

A quick look indicates that there's been a change on the API server side... I will look into this today.

**Comment by jennysjaarda** [comment]
Fantastic, thanks! Since I wasn’t able to follow through with the example, I was just wondering - is this package able to extract formatted full GWAS summary stats from the catalog? They can be downloaded directly from GWAS catalogue, but often they are not consistently formatted, so it would be great to easily access consistently formatted summary stats. Is this package designed for this? Thanks in advance!

**Comment by ramiromagno** [comment]
Hi @jennysjaarda: unfortunately this package won't retrieve the summary stats. I am about to start a new package that will address that question indeed in the next month. The GWAS Catalog actually has separated the two databases, so summary statistics is provided as a separate service, having its own REST API; given that the two are somewhat different I think it is best to have separate clients to access them.

**Comment by ramiromagno** [comment]
@jennysjaarda:
It seems the recent changes to the REST API are more extensive than I expected. The issue here specifically reported should not be too hard to solve but there are other problems popping up now... I have already asked the GWAS Catalog team by email to clarify what were the changes made to server to fully assess what will need fixing. I am sorry for the trouble! It seems you were the first one to detect these problems as it relates to their update.

**Comment by ramiromagno** [comment]
@jennysjaarda: 
The GWAS Catalog got back to me and seemingly they have inadvertently committed changes to the release branch that led to these breaking changes. Meanwhile they have already to revert these changes, and it seems to me that gwasrapidd is working again. Can you confirm that it works for you too so that I can close this issue?

**Comment by ramiromagno** [comment]
@jennysjaarda : can you confirm this issue is now solved for you?
